feat category & products
DigiChanges/node-experience pull request #121
Opened 2023-02-10 01:06 UTC by EnzoDosSantos

2023-02-10 01:08 UTC, Murzbul requested changes

2023-02-10 01:08 UTC, Murzbul commented on src/Category/Infrastructure/Repository/Category.ts
> +        const element = CategoriesMock.find(categorie => categorie._id === id);
Por que estas agregando este mock aca?

2023-02-10 01:08 UTC, Murzbul commented on src/Category/Infrastructure/Repository/Category.ts
> +        const element = CategoriesMock.find(categorie => categorie._id === id);
El mock deberia ser el repository entero. Por ejemplo.

ICategoryRepository -> CategoryMongooseRepository
ICategoryRepository -> CategoryMockRepository

2023-02-10 01:13 UTC, EnzoDosSantos commented on src/Category/Infrastructure/Repository/Category.ts
> +        const element = CategoriesMock.find(categorie => categorie._id === id);
Hola, disculpame pero no te estoy logrando comprender.

2023-02-14 16:26 UTC, EnzoDosSantos commented on src/Category/Infrastructure/Repository/Category.ts
> +        const element = CategoriesMock.find(categorie => categorie._id === id);
Entiendo y coincido totalmente, el problema es que cuento con windows y ahora mismo no cuento con el tiempo ni las herramientas para poder instalar linux y lograr correr correctamente el sistema, por ello lo hice a "ojo" entiendo que no es lo idóneo ni lo que tendría que haber hecho, pero me parecía interesante y quise al menos enviar algo.

2023-02-18 01:10 UTC, closed without merging